version: "3"

services:
  # lecteur:
  #   build: "."
  #   container_name: lecteur
  #   ports:
  #    - 4040:4040
  #   restart: always
  #   links:
  #     - mongo

  mongo:
    image: "mongo:latest"
    container_name: mongo
    ports:
      - "27017:27017"


